apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-staging
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook-staging
    server: "https://c50189b1-bb18-4a46-b772-b045e0ed4fde.k8s.ondigitalocean.com"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/sumanreddyk/argocd-example-apps.git"
    targetRevision: suman
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
