apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/sumanreddyk/argocd-course-apps-definitions.git"
    targetRevision: suman
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
